image: harbor-test.haier.net/paas/node:20-alpine

pages:
  stage: deploy
  script:
    - npm config set registry https://npm.haier.net
    - cd site
    - npm ci
    - npm run build
    - mv .vitepress/dist ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
