/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"strings"
	"time"

	"github.com/cloudwego/eino-ext/devops"
	"github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"

	grpcserver "github.com/superagent-ai/superagent-base/backend/api/grpc"
	cozehandler "github.com/superagent-ai/superagent-base/backend/api/handler/coze"
	"github.com/superagent-ai/superagent-base/backend/api/middleware"
	"github.com/superagent-ai/superagent-base/backend/api/router"
	"github.com/superagent-ai/superagent-base/backend/application"
	"github.com/superagent-ai/superagent-base/backend/infra/cache/impl/redis"
	mysqlpkg "github.com/superagent-ai/superagent-base/backend/infra/orm/impl/mysql"
	"github.com/superagent-ai/superagent-base/backend/pkg/agentdef"
	"github.com/superagent-ai/superagent-base/backend/pkg/evolution"
	"github.com/superagent-ai/superagent-base/backend/pkg/lang/conv"
	"github.com/superagent-ai/superagent-base/backend/pkg/lang/ternary"
	"github.com/superagent-ai/superagent-base/backend/pkg/logs"
	"github.com/superagent-ai/superagent-base/backend/pkg/mcp"
	"github.com/superagent-ai/superagent-base/backend/pkg/memory"
	"github.com/superagent-ai/superagent-base/backend/pkg/memory/builtin"
	"github.com/superagent-ai/superagent-base/backend/pkg/observe"
	"github.com/superagent-ai/superagent-base/backend/pkg/rbac"
	"github.com/superagent-ai/superagent-base/backend/pkg/skill"
	skillbuiltin "github.com/superagent-ai/superagent-base/backend/pkg/skill/builtin"
	"github.com/superagent-ai/superagent-base/backend/pkg/tool"
	"github.com/superagent-ai/superagent-base/backend/pkg/webhook"
	"github.com/superagent-ai/superagent-base/backend/types/consts"
)

func main() {
	ctx := context.Background()
	// Please do not change the order of the function calls below
	setCrashOutput()

	if err := loadEnv(); err != nil {
		logs.Warnf("loadEnv skipped (using environment variables directly): %v", err)
	}

	setLogLevel()

	otelCfg := observe.LoadConfigFromEnv()
	shutdownTracer, err := observe.InitTracer(ctx, otelCfg)
	if err != nil {
		logs.Warnf("InitTracer failed (tracing disabled): %v", err)
		shutdownTracer = func(_ context.Context) error { return nil }
	} else {
		if otelCfg.Enabled {
			logs.Infof("OpenTelemetry tracing enabled (endpoint: %s)", otelCfg.Endpoint)
		}
		if otelCfg.Langfuse.Enabled {
			logs.Infof("Langfuse tracing enabled (host: %s)", otelCfg.Langfuse.Host)
		}
	}
	defer func() { _ = shutdownTracer(ctx) }()

	if err := application.Init(ctx); err != nil {
		panic("InitializeInfra failed, err=" + err.Error())
	}

	// OBS-001: Register Eino observability callback globally so all model/tool
	// invocations automatically report Prometheus metrics and OTel spans.
	callbacks.AppendGlobalHandlers(observe.NewEinoObserveCallback())

	// EVO-001: Initialise local experience self-evolution engine (MySQL-backed).
	// Non-fatal — returns nil when EVOLUTION_ENABLED is false or unset.
	var evoEngine *evolution.Engine
	evoCfg := evolution.LoadConfigFromEnv()
	if evoCfg.Enabled {
		evoDB, evoDBErr := mysqlpkg.New()
		if evoDBErr != nil {
			logs.Warnf("evolution: cannot open MySQL (disabled): %v", evoDBErr)
		} else {
			eng, initErr := evolution.Init(ctx, evoCfg, evoDB)
			if initErr != nil {
				logs.Warnf("evolution engine init failed (disabled): %v", initErr)
			} else {
				evoEngine = eng
				callbacks.AppendGlobalHandlers(evolution.NewEvolutionCallback(evoEngine))
				logs.Infof("evolution engine enabled (local MySQL)")
			}
		}
	}

	// DEV-001: Start Eino DevOps server for IDE graph visualization and debugging.
	// Listens on 127.0.0.1:52538 (local only). Requires "Eino Dev" plugin in VS Code 1.97.x+.
	if err := devops.Init(ctx); err != nil {
		logs.Warnf("eino devops server failed to start (IDE plugin unavailable): %v", err)
	}

	// Initialize SkillManager with marketplace clients + builtin skills.
	var skillMgr *skill.Manager

	// skills.sh marketplace client (enabled by default, no API key required for CLI mode).
	skillsShURL := getEnv("SKILLS_SH_URL", "https://skills.sh")
	skillsShKey := getEnv("SKILLS_SH_API_KEY", "")
	skillsShClient := skill.NewSkillsShClient(skill.SkillsShConfig{
		BaseURL: skillsShURL,
		APIKey:  skillsShKey,
	})
	skillbuiltin.InitFindSkills(skillsShClient)

	// Internal SkillHub client (optional, for enterprise deployments).
	skillHubURL := getEnv("SKILLHUB_URL", "")
	var hubClient skill.HubClient
	if skillHubURL != "" {
		internalHub := skill.NewSkillHubClient(skill.SkillHubClientConfig{
			BaseURL:     skillHubURL,
			AccessToken: getEnv("SKILLHUB_TOKEN", ""),
		})
		hubClient = skill.NewMultiHubClient(internalHub, skillsShClient)
		logs.Infof("SkillHub + skills.sh marketplace initialized: %s + %s", skillHubURL, skillsShURL)
	} else {
		hubClient = skillsShClient
		logs.Infof("skills.sh marketplace initialized: %s", skillsShURL)
	}

	localInvoker := skill.NewLocalInvoker()
	skillbuiltin.RegisterAll(localInvoker)
	compositeInvoker := skill.NewCompositeInvoker(localInvoker, skill.NewHTTPInvoker())
	skillMgr = skill.NewManager(hubClient, compositeInvoker)

	// Pre-register builtin skills so they're accessible via skill://name in agent YAML.
	for _, name := range []string{"datetime", "calculator", "uuid", "find-skills"} {
		skillMgr.RegisterLocal(skill.SkillMeta{
			Name:        name,
			Version:     "1.0.0",
			Description: "Built-in " + name + " skill",
		})
	}

	// Scan .claude/skills/ for SKILL.md files and register them in inline mode.
	// Dir precedence: CLAUDE_SKILLS_DIR env → <cwd>/.claude/skills → <exe-dir>/../.claude/skills.
	claudeSkillsDir := resolveClaudeSkillsDir()
	if claudeSkillsDir != "" {
		n, scanErr := skill.RegisterClaudeSkills(skillMgr, localInvoker, claudeSkillsDir)
		if scanErr != nil {
			logs.Warnf("claude skills: scan failed: %v", scanErr)
		} else {
			logs.Infof("claude skills: registered %d skills from %s", n, claudeSkillsDir)
		}
	}

	// Build the ToolManager and register all built-in tools.
	// Shared between the AgentBuilder (resolves builtin:// refs in YAML) and
	// the gRPC ToolService (exposes registered tools via ListTools/GetTool/InvokeTool).
	toolMgr := tool.NewManager()
	if err := toolMgr.RegisterBuiltins(); err != nil {
		logs.Warnf("tool manager: register builtins failed: %v", err)
	}

	// MCP registry must be created before the AgentBuilder so agents can
	// resolve mcp:// tool references at build time.
	mcpRegistry := mcp.NewRegistry()

	// Shared Redis client — used by memory backend, interrupt checkpoint store, and webhook store.
	// Created once at startup so all subsystems share the same connection pool.
	redisAddr := getEnv("REDIS_ADDR", "127.0.0.1:6379")
	redisPwd := getEnv("REDIS_PASSWORD", "")
	redisClient := redis.NewWithAddrAndPassword(redisAddr, redisPwd)

	// Shared short-term memory backend — used by SessionHandler for conversation history API.
	// Lives outside individual agent scope so any session_id can be queried directly.
	sharedMemBackend := builtin.NewWithCache(redisClient)
	_ = sharedMemBackend.Init(ctx, memory.BackendConfig{Type: "builtin"})
	var sharedMemory memory.Backend = sharedMemBackend

	// Build the AgentRuntime that powers YAML-defined agents.
	// Single builder construction — SkillManager and MCPRegistry conditionally added.
	builderOpts := []agentdef.BuilderOption{
		agentdef.WithModelConfig(agentdef.ModelRuntimeConfig{
			BaseURL: getEnv("MODEL_BASE_URL_0", "http://127.0.0.1:8000/v1"),
			APIKey:  getEnv("MODEL_API_KEY_0", "123456"),
			ModelID: getEnv("MODEL_ID_0", "Qwen3-Coder-Next-4bit"),
		}),
		agentdef.WithMemoryFactory(func(cfg memory.BackendConfig) (memory.Backend, error) {
			b := builtin.NewWithCache(redisClient)
			if err := b.Init(ctx, cfg); err != nil {
				return nil, err
			}
			return b, nil
		}),
		// INJ-001: Inject Redis client so interrupt checkpoint state is stored in Redis,
		// enabling cross-pod resume in multi-replica deployments.
		agentdef.WithRedisClient(redisClient),
	}
	builderOpts = append(builderOpts, agentdef.WithToolManager(toolMgr))
	builderOpts = append(builderOpts, agentdef.WithMCPRegistry(mcpRegistry))
	if skillMgr != nil {
		builderOpts = append(builderOpts, agentdef.WithSkillManager(skillMgr))
	}
	if evoEngine != nil {
		builderOpts = append(builderOpts, agentdef.WithEvolutionAdvisor(evoEngine.Advisor()))
		builderOpts = append(builderOpts, agentdef.WithEvolutionCollector(evoEngine.Collector()))
	}
	agentBuilder := agentdef.NewAgentBuilder(builderOpts...)

	agentRT := agentdef.NewRuntime(agentdef.RuntimeConfig{
		ConfigDir: getEnv("AGENT_CONFIG_DIR", "configs/agents"),
	}, agentBuilder)
	if err := agentRT.Start(ctx); err != nil {
		logs.Warnf("agent runtime start failed (agents unavailable): %v", err)
		agentRT = nil
	}

	// Start gRPC server in background goroutine on port 50051.
	grpcAddr := getEnv("GRPC_LISTEN_ADDR", ":50051")
	agentConfigDir := getEnv("AGENT_CONFIG_DIR", "configs/agents")
	go func() {
		if err := grpcserver.ListenAndServe(grpcAddr, agentRT, toolMgr, agentConfigDir); err != nil {
			logs.Errorf("gRPC server stopped: %v", err)
		}
	}()

	// Initialize RBAC UserStore and seed a default admin user from ADMIN_API_KEY (if set).
	userStore := rbac.NewUserStore()
	if adminKey := os.Getenv("ADMIN_API_KEY"); adminKey != "" {
		userStore.Register(&rbac.User{
			ID:        "admin",
			Name:      "admin",
			Role:      rbac.RoleAdmin,
			APIKey:    adminKey,
			CreatedAt: time.Now(),
		})
	}

	// WHK-001: Initialise webhook dispatcher and register global accessor.
	// WHK-002: Use Redis-backed store when Redis is available so subscriptions survive
	// pod restarts and are visible across all replicas. Falls back to MemoryStore otherwise.
	webhookWorkers := int(conv.StrToInt64D(getEnv("WEBHOOK_WORKERS", "4"), 4))
	var webhookStore webhook.Store
	if redisClient != nil {
		webhookStore = webhook.NewRedisStore(redisClient)
		logs.Infof("webhook store: using Redis backend")
	} else {
		webhookStore = webhook.NewMemoryStore()
		logs.Infof("webhook store: using in-memory backend (Redis unavailable)")
	}
	webhookDispatcher := webhook.NewDispatcher(webhookStore, webhookWorkers)
	webhookDispatcher.Start(ctx)
	webhook.InitGlobalDispatcher(webhookDispatcher)
	logs.Infof("webhook dispatcher started (workers=%d)", webhookWorkers)

	startHttpServer(agentRT, skillMgr, toolMgr, mcpRegistry, userStore, evoEngine, sharedMemory)
}

func startHttpServer(agentRT *agentdef.AgentRuntime, skillMgr *skill.Manager, toolMgr *tool.Manager, mcpRegistry *mcp.Registry, userStore *rbac.UserStore, evoEngine *evolution.Engine, sharedMem memory.Backend) {
	maxRequestBodySize := os.Getenv("MAX_REQUEST_BODY_SIZE")
	maxSize := conv.StrToInt64D(maxRequestBodySize, 1024*1024*200)
	addr := getEnv("LISTEN_ADDR", ":8888")

	opts := []config.Option{
		server.WithHostPorts(addr),
		server.WithMaxRequestBodySize(int(maxSize)),
	}

	useSSL := getEnv(consts.UseSSL, "0")
	if useSSL == "1" {
		cert, err := tls.LoadX509KeyPair(getEnv(consts.SSLCertFile, ""),
			getEnv(consts.SSLKeyFile, ""))
		if err != nil {
			fmt.Println(err.Error())
		}
		cfg := &tls.Config{}
		cfg.Certificates = append(cfg.Certificates, cert)
		opts = append(opts, server.WithTLS(cfg))
		logs.Infof("Use SSL")
	}

	s := server.Default(opts...)

	// cors option
	config := cors.DefaultConfig()
	config.AllowAllOrigins = true
	config.AllowHeaders = []string{"*"}
	corsHandler := cors.New(config)

	// Middleware order matters
	s.Use(middleware.ContextCacheMW())     // must be first
	s.Use(middleware.RequestInspectorMW()) // must be second
	s.Use(middleware.SetHostMW())
	s.Use(middleware.SetLogIDMW())
	s.Use(corsHandler)
	s.Use(middleware.AccessLogMW())
	s.Use(middleware.OpenapiAuthMW())
	s.Use(middleware.SessionAuthMW())
	s.Use(middleware.I18nMW()) // must after SessionAuthMW

	router.GeneratedRegister(s)

	// Infrastructure endpoints — no auth required.
	s.GET("/metrics", observe.MetricsHandler)
	s.GET("/health", func(_ context.Context, ctx *app.RequestContext) {
		ctx.JSON(200, map[string]any{"status": "ok"})
	})
	s.GET("/ready", func(_ context.Context, ctx *app.RequestContext) {
		checks := map[string]string{"http": "ok"}
		if agentRT != nil {
			checks["agent_runtime"] = "ok"
		} else {
			checks["agent_runtime"] = "unavailable"
		}
		allOK := checks["agent_runtime"] == "ok"
		status := 200
		if !allOK {
			status = 503
		}
		ctx.JSON(status, map[string]any{"status": checks})
	})

	// Agent SSE endpoints — direct streaming without the Coze conversation pipeline.
	chatSSE := cozehandler.NewChatSSEHandler(agentRT)
	s.POST("/api/v1/chat/stream", middleware.DeprecationMW("/api/v2"), chatSSE.HandleChatStream)
	s.GET("/api/v1/agents", middleware.DeprecationMW("/api/v2"), chatSSE.HandleListAgents)

	// Admin/monitoring endpoints — protected by AdminAuthMW (key validation + rate limiting).
	adminH := cozehandler.NewAdminHandler(agentRT)
	adminGroup := s.Group("/api/v1/admin", middleware.APIKeyAdminAuthMW(userStore), middleware.DeprecationMW("/api/v2"))
	adminGroup.GET("/status", adminH.HandleStatus)
	adminGroup.POST("/reload", adminH.HandleReload)
	adminGroup.GET("/logs", adminH.HandleLogStream)

	// Agent CRUD endpoints — read requires agents:read, mutations require agents:write/delete.
	agentAdmin := cozehandler.NewAgentAdminHandler(agentRT, getEnv("AGENT_CONFIG_DIR", "configs/agents"))
	adminGroup.GET("/agents", middleware.RequirePermission("agents", "read"), agentAdmin.HandleList)
	adminGroup.POST("/agents/validate", middleware.RequirePermission("agents", "read"), agentAdmin.HandleValidate)
	adminGroup.GET("/agents/:name", middleware.RequirePermission("agents", "read"), agentAdmin.HandleGet)
	adminGroup.POST("/agents", middleware.RequirePermission("agents", "write"), agentAdmin.HandleCreate)
	adminGroup.PUT("/agents/:name", middleware.RequirePermission("agents", "write"), agentAdmin.HandleUpdate)
	adminGroup.DELETE("/agents/:name", middleware.RequirePermission("agents", "delete"), agentAdmin.HandleDelete)

	// User CRUD endpoints — full admin role required (no extra per-route permission; admin group auth suffices).
	userAdmin := cozehandler.NewUserAdminHandler(userStore)
	adminGroup.GET("/users", userAdmin.HandleList)
	adminGroup.POST("/users", userAdmin.HandleCreate)
	adminGroup.PUT("/users/:id", userAdmin.HandleUpdate)
	adminGroup.DELETE("/users/:id", userAdmin.HandleDelete)

	// MCP server management endpoints — protected by admin auth middleware.
	mcpAdmin := cozehandler.NewMCPAdminHandler(mcpRegistry)
	adminGroup.GET("/mcp/servers", mcpAdmin.HandleList)
	adminGroup.POST("/mcp/servers", middleware.RequirePermission("config", "write"), mcpAdmin.HandleConnect)
	adminGroup.DELETE("/mcp/servers/:name", middleware.RequirePermission("config", "write"), mcpAdmin.HandleDisconnect)
	adminGroup.GET("/mcp/servers/:name/tools", mcpAdmin.HandleListTools)

	// Evolution management endpoints — read-only queries; no data mutation.
	evoAdmin := cozehandler.NewEvolutionAdminHandler(evoEngine)
	adminGroup.GET("/evolution/stats", evoAdmin.HandleStats)
	adminGroup.GET("/evolution/genes", evoAdmin.HandleListGenes)
	adminGroup.GET("/evolution/federated", evoAdmin.HandleFederatedSearch)

	// Webhook subscription management endpoints — protected by admin auth middleware.
	webhookH := cozehandler.NewWebhookHandler(webhook.GetWebhookDispatcher())
	adminGroup.POST("/webhooks", webhookH.HandleCreate)
	adminGroup.GET("/webhooks", webhookH.HandleList)
	adminGroup.GET("/webhooks/:id", webhookH.HandleGet)
	adminGroup.PUT("/webhooks/:id", webhookH.HandleUpdate)
	adminGroup.DELETE("/webhooks/:id", webhookH.HandleDelete)
	adminGroup.POST("/webhooks/:id/test", webhookH.HandleTest)
	adminGroup.GET("/webhooks/:id/logs", webhookH.HandleLogs)

	// 集团小海对接接口 (集团IT智能体输出规范 v1.0.0) — Api-Key 鉴权.
	xiaohaiH := cozehandler.NewXiaohaiHandler(agentRT)
	xiaohaiGroup := s.Group("/api/v1/xiaohai")
	xiaohaiGroup.POST("/stream/:agent_id", xiaohaiH.HandleStream)
	xiaohaiGroup.POST("/chat/:agent_id", xiaohaiH.HandleNonStream)

	// Session history — conversation message read/clear (backed by shared Redis memory).
	sessionH := cozehandler.NewSessionHandler(sharedMem)
	s.GET("/api/v1/sessions/:session_id/messages", middleware.DeprecationMW("/api/v2"), sessionH.HandleGetMessages)
	s.DELETE("/api/v1/sessions/:session_id", middleware.APIKeyAdminAuthMW(userStore), middleware.DeprecationMW("/api/v2"), sessionH.HandleClearSession)

	// File management — multipart upload, list, download, delete (local filesystem).
	uploadDir := getEnv("UPLOAD_DIR", filepath.Join("bin", "uploads"))
	fileH := cozehandler.NewFileHandler(uploadDir)
	s.POST("/api/v1/files", middleware.DeprecationMW("/api/v2"), fileH.HandleUpload)
	s.GET("/api/v1/files", middleware.DeprecationMW("/api/v2"), fileH.HandleList)
	s.GET("/api/v1/files/:id", middleware.DeprecationMW("/api/v2"), fileH.HandleGet)
	s.GET("/api/v1/files/:id/content", middleware.DeprecationMW("/api/v2"), fileH.HandleDownload)
	s.DELETE("/api/v1/files/:id", middleware.APIKeyAdminAuthMW(userStore), middleware.DeprecationMW("/api/v2"), fileH.HandleDelete)

	// Skill management API endpoints (v1, deprecated).
	registerSkillRoutes(s, skillMgr, userStore)

	// Memory handler — backed by the shared Redis memory store.
	memH := cozehandler.NewMemoryHandler(sharedMem)

	// V1 interrupt/resume/abort — same handlers as v2 (deprecated).
	s.POST("/api/v1/chat/resume", middleware.DeprecationMW("/api/v2"), chatSSE.HandleChatResume)
	s.GET("/api/v1/chat/interrupt_state", middleware.DeprecationMW("/api/v2"), chatSSE.HandleGetInterruptState)
	s.POST("/api/v1/chat/abort", middleware.DeprecationMW("/api/v2"), chatSSE.HandleChatAbort)

	// V2 canonical API — same handlers, no deprecation headers.
	registerV2Routes(s, chatSSE, adminH, agentAdmin, userAdmin, mcpAdmin, evoAdmin, webhookH, xiaohaiH, sessionH, fileH, skillMgr, toolMgr, memH, userStore)

	s.Spin()
}

// registerV2Routes registers all v2 canonical routes using the same handlers as v1.
// v2 routes do not carry deprecation headers.
func registerV2Routes(
	s *server.Hertz,
	chatSSE *cozehandler.ChatSSEHandler,
	adminH *cozehandler.AdminHandler,
	agentAdmin *cozehandler.AgentAdminHandler,
	userAdmin *cozehandler.UserAdminHandler,
	mcpAdmin *cozehandler.MCPAdminHandler,
	evoAdmin *cozehandler.EvolutionAdminHandler,
	webhookH *cozehandler.WebhookHandler,
	xiaohaiH *cozehandler.XiaohaiHandler,
	sessionH *cozehandler.SessionHandler,
	fileH *cozehandler.FileHandler,
	skillMgr *skill.Manager,
	toolMgr *tool.Manager,
	memH *cozehandler.MemoryHandler,
	userStore *rbac.UserStore,
) {
	// Chat endpoints.
	s.POST("/api/v2/chat/stream", chatSSE.HandleChatStream)
	s.POST("/api/v2/chat/resume", chatSSE.HandleChatResume)
	s.GET("/api/v2/chat/interrupt_state", chatSSE.HandleGetInterruptState)
	s.POST("/api/v2/chat/abort", chatSSE.HandleChatAbort)
	s.GET("/api/v2/agents", chatSSE.HandleListAgents)

	// Session history — read is public, clear requires admin auth.
	s.GET("/api/v2/sessions/:session_id/messages", sessionH.HandleGetMessages)
	s.DELETE("/api/v2/sessions/:session_id", middleware.APIKeyAdminAuthMW(userStore), sessionH.HandleClearSession)

	// File management — upload/list/get are public; delete requires admin auth.
	s.POST("/api/v2/files", fileH.HandleUpload)
	s.GET("/api/v2/files", fileH.HandleList)
	s.GET("/api/v2/files/:id", fileH.HandleGet)
	s.GET("/api/v2/files/:id/content", fileH.HandleDownload)
	s.DELETE("/api/v2/files/:id", middleware.APIKeyAdminAuthMW(userStore), fileH.HandleDelete)

	// User profile — returns the authenticated caller's identity.
	s.GET("/api/v2/me", middleware.APIKeyAdminAuthMW(userStore), func(ctx context.Context, c *app.RequestContext) {
		user := rbac.GetUser(ctx)
		if user == nil {
			c.JSON(401, map[string]any{"error": "unauthorized"})
			return
		}
		c.JSON(200, map[string]any{"user": user})
	})

	// Admin/monitoring endpoints — same auth as v1.
	adminGroup := s.Group("/api/v2/admin", middleware.APIKeyAdminAuthMW(userStore))
	adminGroup.GET("/status", adminH.HandleStatus)
	adminGroup.POST("/reload", adminH.HandleReload)
	adminGroup.GET("/logs", adminH.HandleLogStream)

	// Agent CRUD.
	adminGroup.GET("/agents", middleware.RequirePermission("agents", "read"), agentAdmin.HandleList)
	adminGroup.POST("/agents/validate", middleware.RequirePermission("agents", "read"), agentAdmin.HandleValidate)
	adminGroup.GET("/agents/:name", middleware.RequirePermission("agents", "read"), agentAdmin.HandleGet)
	adminGroup.POST("/agents", middleware.RequirePermission("agents", "write"), agentAdmin.HandleCreate)
	adminGroup.PUT("/agents/:name", middleware.RequirePermission("agents", "write"), agentAdmin.HandleUpdate)
	adminGroup.DELETE("/agents/:name", middleware.RequirePermission("agents", "delete"), agentAdmin.HandleDelete)

	// User CRUD.
	adminGroup.GET("/users", userAdmin.HandleList)
	adminGroup.POST("/users", userAdmin.HandleCreate)
	adminGroup.PUT("/users/:id", userAdmin.HandleUpdate)
	adminGroup.DELETE("/users/:id", userAdmin.HandleDelete)

	// MCP server management.
	adminGroup.GET("/mcp/servers", mcpAdmin.HandleList)
	adminGroup.POST("/mcp/servers", middleware.RequirePermission("config", "write"), mcpAdmin.HandleConnect)
	adminGroup.DELETE("/mcp/servers/:name", middleware.RequirePermission("config", "write"), mcpAdmin.HandleDisconnect)
	adminGroup.GET("/mcp/servers/:name/tools", mcpAdmin.HandleListTools)

	// Evolution management.
	adminGroup.GET("/evolution/stats", evoAdmin.HandleStats)
	adminGroup.GET("/evolution/genes", evoAdmin.HandleListGenes)
	adminGroup.GET("/evolution/federated", evoAdmin.HandleFederatedSearch)
	adminGroup.POST("/evolution/recommend", evoAdmin.HandleRecommend)

	// Webhook management.
	adminGroup.POST("/webhooks", webhookH.HandleCreate)
	adminGroup.GET("/webhooks", webhookH.HandleList)
	adminGroup.GET("/webhooks/:id", webhookH.HandleGet)
	adminGroup.PUT("/webhooks/:id", webhookH.HandleUpdate)
	adminGroup.DELETE("/webhooks/:id", webhookH.HandleDelete)
	adminGroup.POST("/webhooks/:id/test", webhookH.HandleTest)
	adminGroup.GET("/webhooks/:id/logs", webhookH.HandleLogs)

	// 集团小海 — v2 path uses same handlers.
	xiaohaiGroup := s.Group("/api/v2/xiaohai")
	xiaohaiGroup.POST("/stream/:agent_id", xiaohaiH.HandleStream)
	xiaohaiGroup.POST("/chat/:agent_id", xiaohaiH.HandleNonStream)

	// Long-term memory — user_id scoped; read is public, mutations are public.
	s.GET("/api/v2/memory/long-term", memH.HandleLTMList)
	s.POST("/api/v2/memory/long-term", memH.HandleLTMAdd)
	s.GET("/api/v2/memory/long-term/search", memH.HandleLTMSearch)
	s.PUT("/api/v2/memory/long-term/:id", memH.HandleLTMUpdate)
	s.DELETE("/api/v2/memory/long-term/:id", middleware.APIKeyAdminAuthMW(userStore), memH.HandleLTMDelete)

	// Agent state — per-agent key-value store.
	s.GET("/api/v2/agents/:agent_id/state", memH.HandleAgentStateGetAll)
	s.GET("/api/v2/agents/:agent_id/state/:key", memH.HandleAgentStateGet)
	s.POST("/api/v2/agents/:agent_id/state", memH.HandleAgentStateSet)
	s.DELETE("/api/v2/agents/:agent_id/state/:key", middleware.APIKeyAdminAuthMW(userStore), memH.HandleAgentStateDelete)

	// Tool registry — list all tools registered in the runtime.
	registerToolV2Routes(s, toolMgr)

	// Skill management (v2).
	registerSkillV2Routes(s, skillMgr, userStore)

	// Conversation CRUD v2 — wraps conversation_service.go OpenAPI functions.
	s.GET("/api/v2/conversations", cozehandler.ListConversationsApi)
	s.POST("/api/v2/conversations", cozehandler.CreateConversation)
	s.GET("/api/v2/conversations/:id", cozehandler.RetrieveConversationApi)
	s.PUT("/api/v2/conversations/:id", cozehandler.UpdateConversationApi)
	s.DELETE("/api/v2/conversations/:id", middleware.APIKeyAdminAuthMW(userStore), cozehandler.DeleteConversationApi)

	// Message access v2 — wraps message_service.go functions.
	s.GET("/api/v2/conversations/:conversation_id/messages", cozehandler.GetApiMessageList)
	s.DELETE("/api/v2/conversations/:conversation_id/messages/:message_id", middleware.APIKeyAdminAuthMW(userStore), cozehandler.DeleteMessage)

	// Workflow execution v2 (runtime only) — wraps workflow_service.go OpenAPI* functions.
	s.POST("/api/v2/workflows/run", cozehandler.OpenAPIRunFlow)
	s.POST("/api/v2/workflows/stream_run", cozehandler.OpenAPIStreamRunFlow)
	s.POST("/api/v2/workflows/stream_resume", cozehandler.OpenAPIStreamResumeFlow)
	s.POST("/api/v2/workflows/chat", cozehandler.OpenAPIChatFlowRun)
	s.GET("/api/v2/workflows/:workflow_id", cozehandler.OpenAPIGetWorkflowInfo)
}

func registerSkillV2Routes(s *server.Hertz, mgr *skill.Manager, userStore *rbac.UserStore) {
	if mgr == nil {
		return
	}

	// GET /api/v2/skills
	s.GET("/api/v2/skills", func(c context.Context, ctx *app.RequestContext) {
		installed := mgr.ListInstalled()
		items := make([]map[string]any, 0, len(installed))
		for _, inst := range installed {
			items = append(items, map[string]any{
				"name":        inst.Meta.Name,
				"version":     inst.Meta.Version,
				"description": inst.Meta.Description,
				"status":      inst.Status,
			})
		}
		ctx.JSON(200, map[string]any{"skills": items})
	})

	// GET /api/v2/skills/search?q=
	s.GET("/api/v2/skills/search", func(c context.Context, ctx *app.RequestContext) {
		query := string(ctx.QueryArgs().Peek("q"))
		if query == "" {
			ctx.JSON(400, map[string]any{"error": "query parameter 'q' is required"})
			return
		}
		results, err := mgr.Search(c, query, skill.SearchOpts{Limit: 20})
		if err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"skills": results})
	})

	skillAdmin := s.Group("/api/v2/skills",
		middleware.APIKeyAdminAuthMW(userStore),
		middleware.RequirePermission("config", "write"),
	)

	skillAdmin.POST("/install", func(c context.Context, ctx *app.RequestContext) {
		var req struct {
			Name    string `json:"name"`
			Version string `json:"version"`
		}
		if err := ctx.BindJSON(&req); err != nil {
			ctx.JSON(400, map[string]any{"error": "invalid request body"})
			return
		}
		if req.Name == "" {
			ctx.JSON(400, map[string]any{"error": "name is required"})
			return
		}
		if req.Version == "" {
			req.Version = "latest"
		}
		if err := mgr.Install(c, req.Name, req.Version); err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"status": "installed", "name": req.Name, "version": req.Version})
	})

	skillAdmin.DELETE("/:name", func(_ context.Context, ctx *app.RequestContext) {
		name := ctx.Param("name")
		mgr.Uninstall(name)
		ctx.JSON(200, map[string]any{"status": "uninstalled", "name": name})
	})
}

func registerSkillRoutes(s *server.Hertz, mgr *skill.Manager, userStore *rbac.UserStore) {
	if mgr == nil {
		return
	}

	// GET /api/v1/skills — list installed skills (public, no auth required)
	s.GET("/api/v1/skills", middleware.DeprecationMW("/api/v2"), func(c context.Context, ctx *app.RequestContext) {
		installed := mgr.ListInstalled()
		items := make([]map[string]any, 0, len(installed))
		for _, inst := range installed {
			items = append(items, map[string]any{
				"name":        inst.Meta.Name,
				"version":     inst.Meta.Version,
				"description": inst.Meta.Description,
				"status":      inst.Status,
			})
		}
		ctx.JSON(200, map[string]any{"skills": items})
	})

	// GET /api/v1/skills/search?q= — search SkillHub (public, no auth required)
	s.GET("/api/v1/skills/search", middleware.DeprecationMW("/api/v2"), func(c context.Context, ctx *app.RequestContext) {
		query := string(ctx.QueryArgs().Peek("q"))
		if query == "" {
			ctx.JSON(400, map[string]any{"error": "query parameter 'q' is required"})
			return
		}
		results, err := mgr.Search(c, query, skill.SearchOpts{Limit: 20})
		if err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"skills": results})
	})

	// Mutating skill routes — protected by APIKeyAdminAuthMW + config:write permission.
	skillAdmin := s.Group("/api/v1/skills",
		middleware.APIKeyAdminAuthMW(userStore),
		middleware.RequirePermission("config", "write"),
		middleware.DeprecationMW("/api/v2"),
	)

	// POST /api/v1/skills/install — install a skill
	skillAdmin.POST("/install", func(c context.Context, ctx *app.RequestContext) {
		var req struct {
			Name    string `json:"name"`
			Version string `json:"version"`
		}
		if err := ctx.BindJSON(&req); err != nil {
			ctx.JSON(400, map[string]any{"error": "invalid request body"})
			return
		}
		if req.Name == "" {
			ctx.JSON(400, map[string]any{"error": "name is required"})
			return
		}
		if req.Version == "" {
			req.Version = "latest"
		}
		if err := mgr.Install(c, req.Name, req.Version); err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"status": "installed", "name": req.Name, "version": req.Version})
	})

	// DELETE /api/v1/skills/:name — uninstall a skill
	skillAdmin.DELETE("/:name", func(_ context.Context, ctx *app.RequestContext) {
		name := ctx.Param("name")
		mgr.Uninstall(name)
		ctx.JSON(200, map[string]any{"status": "uninstalled", "name": name})
	})
}

func registerToolV2Routes(s *server.Hertz, mgr *tool.Manager) {
	if mgr == nil {
		return
	}

	// GET /api/v2/tools — list all registered tools with their schemas.
	s.GET("/api/v2/tools", func(ctx context.Context, c *app.RequestContext) {
		tools := mgr.List()
		items := make([]map[string]any, 0, len(tools))
		for _, t := range tools {
			info, err := t.Info(ctx)
			if err != nil {
				continue
			}
			item := map[string]any{
				"name":        info.Name,
				"description": info.Desc,
			}
			if info.Extra != nil {
				item["extra"] = info.Extra
			}
			items = append(items, item)
		}
		c.JSON(200, map[string]any{"tools": items, "count": len(items)})
	})
}

func loadEnv() (err error) {
	appEnv := os.Getenv("APP_ENV")
	fileName := ternary.IFElse(appEnv == "", ".env", ".env."+appEnv)

	logs.Infof("load env file: %s", fileName)

	err = godotenv.Load(fileName)
	if err != nil {
		return fmt.Errorf("load env file(%s) failed, err=%w", fileName, err)
	}

	return err
}

// resolveClaudeSkillsDir returns the directory that contains Claude Code SKILL.md files.
// Resolution order:
//  1. CLAUDE_SKILLS_DIR env var (explicit override)
//  2. Walk up from cwd looking for .claude/skills (handles `cd backend && go run .`)
//  3. Walk up from exe dir looking for .claude/skills (deployment layout)
//  4. /skills (system-wide fallback)
func resolveClaudeSkillsDir() string {
	if dir := os.Getenv("CLAUDE_SKILLS_DIR"); dir != "" {
		return dir
	}
	// Walk up from cwd — handles both project-root and backend/ launch paths.
	if cwd, err := os.Getwd(); err == nil {
		if dir := walkUpForSkills(cwd); dir != "" {
			return dir
		}
	}
	// Walk up from the executable's real path.
	if exe, err := os.Executable(); err == nil {
		if dir := walkUpForSkills(filepath.Dir(exe)); dir != "" {
			return dir
		}
	}
	// System-wide fallback.
	return "/skills"
}

// walkUpForSkills traverses from start toward the filesystem root, stopping at
// the first directory that contains a .claude/skills subdirectory.
// Stops after 8 levels to avoid unbounded traversal.
func walkUpForSkills(start string) string {
	dir := start
	for i := 0; i < 8; i++ {
		candidate := filepath.Join(dir, ".claude", "skills")
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return candidate
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break // reached filesystem root
		}
		dir = parent
	}
	return ""
}

func getEnv(key string, defaultValue string) string {
	v := os.Getenv(key)
	if v == "" {
		return defaultValue
	}
	return v
}

func setLogLevel() {
	level := strings.ToLower(os.Getenv("LOG_LEVEL"))

	logs.Infof("log level: %s", level)
	switch level {
	case "trace":
		logs.SetLevel(logs.LevelTrace)
	case "debug":
		logs.SetLevel(logs.LevelDebug)
	case "info":
		logs.SetLevel(logs.LevelInfo)
	case "notice":
		logs.SetLevel(logs.LevelNotice)
	case "warn":
		logs.SetLevel(logs.LevelWarn)
	case "error":
		logs.SetLevel(logs.LevelError)
	case "fatal":
		logs.SetLevel(logs.LevelFatal)
	default:
		logs.SetLevel(logs.LevelInfo)
	}
}

func setCrashOutput() {
	crashFile, _ := os.Create("crash.log")
	debug.SetCrashOutput(crashFile, debug.CrashOptions{})
}
