/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package main

import (
	"context"
	"crypto/tls"
	"fmt"
	"os"
	"runtime/debug"
	"strings"

	"github.com/cloudwego/eino-ext/devops"
	"github.com/cloudwego/eino/callbacks"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"

	grpcserver "github.com/superagent-ai/superagent-base/backend/api/grpc"
	cozehandler "github.com/superagent-ai/superagent-base/backend/api/handler/coze"
	"github.com/superagent-ai/superagent-base/backend/api/middleware"
	"github.com/superagent-ai/superagent-base/backend/api/router"
	"github.com/superagent-ai/superagent-base/backend/application"
	"github.com/superagent-ai/superagent-base/backend/pkg/agentdef"
	"github.com/superagent-ai/superagent-base/backend/pkg/memory"
	"github.com/superagent-ai/superagent-base/backend/pkg/memory/builtin"
	"github.com/superagent-ai/superagent-base/backend/pkg/skill"
	skillbuiltin "github.com/superagent-ai/superagent-base/backend/pkg/skill/builtin"
	"github.com/superagent-ai/superagent-base/backend/infra/cache/impl/redis"
	"github.com/superagent-ai/superagent-base/backend/pkg/lang/conv"
	"github.com/superagent-ai/superagent-base/backend/pkg/lang/ternary"
	"github.com/superagent-ai/superagent-base/backend/pkg/logs"
	"github.com/superagent-ai/superagent-base/backend/pkg/observe"
	"github.com/superagent-ai/superagent-base/backend/types/consts"
)

func main() {
	ctx := context.Background()
	// Please do not change the order of the function calls below
	setCrashOutput()

	if err := loadEnv(); err != nil {
		logs.Warnf("loadEnv skipped (using environment variables directly): %v", err)
	}

	setLogLevel()

	shutdownTracer, err := observe.InitTracer(ctx, observe.LoadConfigFromEnv())
	if err != nil {
		logs.Warnf("InitTracer failed (tracing disabled): %v", err)
		shutdownTracer = func(_ context.Context) error { return nil }
	}
	defer func() { _ = shutdownTracer(ctx) }()

	if err := application.Init(ctx); err != nil {
		panic("InitializeInfra failed, err=" + err.Error())
	}

	// OBS-001: Register Eino observability callback globally so all model/tool
	// invocations automatically report Prometheus metrics and OTel spans.
	callbacks.AppendGlobalHandlers(observe.NewEinoObserveCallback())

	// DEV-001: Start Eino DevOps server for IDE graph visualization and debugging.
	// Listens on 127.0.0.1:52538 (local only). Requires "Eino Dev" plugin in VS Code 1.97.x+.
	if err := devops.Init(ctx); err != nil {
		logs.Warnf("eino devops server failed to start (IDE plugin unavailable): %v", err)
	}

	// Initialize SkillManager with internal SkillHub client + builtin skills.
	var skillMgr *skill.Manager
	skillHubURL := getEnv("SKILLHUB_URL", "")
	if skillHubURL != "" {
		hubClient := skill.NewSkillHubClient(skill.SkillHubClientConfig{
			BaseURL:     skillHubURL,
			AccessToken: getEnv("SKILLHUB_TOKEN", ""),
		})
		localInvoker := skill.NewLocalInvoker()
		skillbuiltin.RegisterAll(localInvoker)
		httpInvoker := skill.NewHTTPInvoker()
		compositeInvoker := skill.NewCompositeInvoker(localInvoker, httpInvoker)
		skillMgr = skill.NewManager(hubClient, compositeInvoker)
		logs.Infof("SkillHub client initialized: %s", skillHubURL)
	} else {
		// Even without SkillHub, register builtin skills.
		localInvoker := skill.NewLocalInvoker()
		skillbuiltin.RegisterAll(localInvoker)
		compositeInvoker := skill.NewCompositeInvoker(localInvoker, skill.NewHTTPInvoker())
		skillMgr = skill.NewManager(nil, compositeInvoker)
	}

	// Pre-register builtin skills so they're accessible via skill://name in agent YAML.
	for _, name := range []string{"datetime", "calculator", "uuid"} {
		skillMgr.RegisterLocal(skill.SkillMeta{
			Name:        name,
			Version:     "1.0.0",
			Description: "Built-in " + name + " skill",
		})
	}

	// Build the AgentRuntime that powers YAML-defined agents.
	// Single builder construction — SkillManager is conditionally added.
	builderOpts := []agentdef.BuilderOption{
		agentdef.WithModelConfig(agentdef.ModelRuntimeConfig{
			BaseURL: getEnv("MODEL_BASE_URL_0", "http://127.0.0.1:8000/v1"),
			APIKey:  getEnv("MODEL_API_KEY_0", "123456"),
			ModelID: getEnv("MODEL_ID_0", "Qwen3-Coder-Next-4bit"),
		}),
		agentdef.WithMemoryFactory(func(cfg memory.BackendConfig) (memory.Backend, error) {
			redisAddr := getEnv("REDIS_ADDR", "127.0.0.1:6379")
			redisPwd := getEnv("REDIS_PASSWORD", "")
			c := redis.NewWithAddrAndPassword(redisAddr, redisPwd)
			b := builtin.NewWithCache(c)
			if err := b.Init(ctx, cfg); err != nil {
				return nil, err
			}
			return b, nil
		}),
	}
	if skillMgr != nil {
		builderOpts = append(builderOpts, agentdef.WithSkillManager(skillMgr))
	}
	agentBuilder := agentdef.NewAgentBuilder(builderOpts...)

	agentRT := agentdef.NewRuntime(agentdef.RuntimeConfig{
		ConfigDir: getEnv("AGENT_CONFIG_DIR", "configs/agents"),
	}, agentBuilder)
	if err := agentRT.Start(ctx); err != nil {
		logs.Warnf("agent runtime start failed (agents unavailable): %v", err)
		agentRT = nil
	}

	// Start gRPC server in background goroutine on port 50051.
	grpcAddr := getEnv("GRPC_LISTEN_ADDR", ":50051")
	go func() {
		if err := grpcserver.ListenAndServe(grpcAddr, agentRT); err != nil {
			logs.Errorf("gRPC server stopped: %v", err)
		}
	}()

	startHttpServer(agentRT, skillMgr)
}

func startHttpServer(agentRT *agentdef.AgentRuntime, skillMgr *skill.Manager) {
	maxRequestBodySize := os.Getenv("MAX_REQUEST_BODY_SIZE")
	maxSize := conv.StrToInt64D(maxRequestBodySize, 1024*1024*200)
	addr := getEnv("LISTEN_ADDR", ":8888")

	opts := []config.Option{
		server.WithHostPorts(addr),
		server.WithMaxRequestBodySize(int(maxSize)),
	}

	useSSL := getEnv(consts.UseSSL, "0")
	if useSSL == "1" {
		cert, err := tls.LoadX509KeyPair(getEnv(consts.SSLCertFile, ""),
			getEnv(consts.SSLKeyFile, ""))
		if err != nil {
			fmt.Println(err.Error())
		}
		cfg := &tls.Config{}
		cfg.Certificates = append(cfg.Certificates, cert)
		opts = append(opts, server.WithTLS(cfg))
		logs.Infof("Use SSL")
	}

	s := server.Default(opts...)

	// cors option
	config := cors.DefaultConfig()
	config.AllowAllOrigins = true
	config.AllowHeaders = []string{"*"}
	corsHandler := cors.New(config)

	// Middleware order matters
	s.Use(middleware.ContextCacheMW())     // must be first
	s.Use(middleware.RequestInspectorMW()) // must be second
	s.Use(middleware.SetHostMW())
	s.Use(middleware.SetLogIDMW())
	s.Use(corsHandler)
	s.Use(middleware.AccessLogMW())
	s.Use(middleware.OpenapiAuthMW())
	s.Use(middleware.SessionAuthMW())
	s.Use(middleware.I18nMW()) // must after SessionAuthMW

	router.GeneratedRegister(s)

	// Infrastructure endpoints — no auth required.
	s.GET("/metrics", observe.MetricsHandler)
	s.GET("/health", func(_ context.Context, ctx *app.RequestContext) {
		ctx.JSON(200, map[string]any{"status": "ok"})
	})
	s.GET("/ready", func(_ context.Context, ctx *app.RequestContext) {
		checks := map[string]string{"http": "ok"}
		if agentRT != nil {
			checks["agent_runtime"] = "ok"
		} else {
			checks["agent_runtime"] = "unavailable"
		}
		allOK := checks["agent_runtime"] == "ok"
		status := 200
		if !allOK {
			status = 503
		}
		ctx.JSON(status, map[string]any{"status": checks})
	})

	// Agent SSE endpoints — direct streaming without the Coze conversation pipeline.
	chatSSE := cozehandler.NewChatSSEHandler(agentRT)
	s.POST("/api/v1/chat/stream", chatSSE.HandleChatStream)
	s.GET("/api/v1/agents", chatSSE.HandleListAgents)

	// Admin/monitoring endpoints.
	if getEnv("ADMIN_API_KEY", "") == "" {
		logs.Warnf("⚠️  ADMIN_API_KEY is not set — admin endpoints (/api/v1/admin/*) are UNPROTECTED. Set ADMIN_API_KEY for production!")
	}
	adminH := cozehandler.NewAdminHandler(agentRT)
	s.GET("/api/v1/admin/status", adminH.HandleStatus)
	s.POST("/api/v1/admin/reload", adminH.HandleReload)
	s.GET("/api/v1/admin/logs", adminH.HandleLogStream)

	// Skill management API endpoints.
	registerSkillRoutes(s, skillMgr)

	s.Spin()
}

func registerSkillRoutes(s *server.Hertz, mgr *skill.Manager) {
	if mgr == nil {
		return
	}

	// GET /api/v1/skills — list installed skills
	s.GET("/api/v1/skills", func(c context.Context, ctx *app.RequestContext) {
		installed := mgr.ListInstalled()
		items := make([]map[string]any, 0, len(installed))
		for _, inst := range installed {
			items = append(items, map[string]any{
				"name":        inst.Meta.Name,
				"version":     inst.Meta.Version,
				"description": inst.Meta.Description,
				"status":      inst.Status,
			})
		}
		ctx.JSON(200, map[string]any{"skills": items})
	})

	// GET /api/v1/skills/search?q= — search SkillHub
	s.GET("/api/v1/skills/search", func(c context.Context, ctx *app.RequestContext) {
		query := string(ctx.QueryArgs().Peek("q"))
		if query == "" {
			ctx.JSON(400, map[string]any{"error": "query parameter 'q' is required"})
			return
		}
		results, err := mgr.Search(c, query, skill.SearchOpts{Limit: 20})
		if err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"skills": results})
	})

	// POST /api/v1/skills/install — install a skill (protected by ADMIN_API_KEY)
	s.POST("/api/v1/skills/install", func(c context.Context, ctx *app.RequestContext) {
		if !cozehandler.CheckAdminAuth(ctx) {
			return
		}
		var req struct {
			Name    string `json:"name"`
			Version string `json:"version"`
		}
		if err := ctx.BindJSON(&req); err != nil {
			ctx.JSON(400, map[string]any{"error": "invalid request body"})
			return
		}
		if req.Name == "" {
			ctx.JSON(400, map[string]any{"error": "name is required"})
			return
		}
		if req.Version == "" {
			req.Version = "latest"
		}
		if err := mgr.Install(c, req.Name, req.Version); err != nil {
			ctx.JSON(502, map[string]any{"error": err.Error()})
			return
		}
		ctx.JSON(200, map[string]any{"status": "installed", "name": req.Name, "version": req.Version})
	})

	// DELETE /api/v1/skills/:name — uninstall a skill (protected by ADMIN_API_KEY)
	s.DELETE("/api/v1/skills/:name", func(_ context.Context, ctx *app.RequestContext) {
		if !cozehandler.CheckAdminAuth(ctx) {
			return
		}
		name := ctx.Param("name")
		mgr.Uninstall(name)
		ctx.JSON(200, map[string]any{"status": "uninstalled", "name": name})
	})
}

func loadEnv() (err error) {
	appEnv := os.Getenv("APP_ENV")
	fileName := ternary.IFElse(appEnv == "", ".env", ".env."+appEnv)

	logs.Infof("load env file: %s", fileName)

	err = godotenv.Load(fileName)
	if err != nil {
		return fmt.Errorf("load env file(%s) failed, err=%w", fileName, err)
	}

	return err
}

func getEnv(key string, defaultValue string) string {
	v := os.Getenv(key)
	if v == "" {
		return defaultValue
	}
	return v
}

func setLogLevel() {
	level := strings.ToLower(os.Getenv("LOG_LEVEL"))

	logs.Infof("log level: %s", level)
	switch level {
	case "trace":
		logs.SetLevel(logs.LevelTrace)
	case "debug":
		logs.SetLevel(logs.LevelDebug)
	case "info":
		logs.SetLevel(logs.LevelInfo)
	case "notice":
		logs.SetLevel(logs.LevelNotice)
	case "warn":
		logs.SetLevel(logs.LevelWarn)
	case "error":
		logs.SetLevel(logs.LevelError)
	case "fatal":
		logs.SetLevel(logs.LevelFatal)
	default:
		logs.SetLevel(logs.LevelInfo)
	}
}

func setCrashOutput() {
	crashFile, _ := os.Create("crash.log")
	debug.SetCrashOutput(crashFile, debug.CrashOptions{})
}
