"""
Generate a Markdown summary report from pytest output and screenshots.
"""
import os
import re
from pathlib import Path
from datetime import datetime


def parse_test_output(log_path: str) -> dict:
    """Parse pytest verbose output to extract test results."""
    results = {"passed": [], "failed": [], "skipped": [], "errors": []}

    if not os.path.exists(log_path):
        return results

    with open(log_path, "r") as f:
        content = f.read()

    # Parse PASSED/FAILED/SKIPPED lines
    for line in content.split("\n"):
        if " PASSED" in line:
            match = re.search(r"(test_\S+)", line)
            if match:
                results["passed"].append(match.group(1))
        elif " FAILED" in line:
            match = re.search(r"(test_\S+)", line)
            if match:
                results["failed"].append(match.group(1))
        elif " SKIPPED" in line:
            match = re.search(r"(test_\S+)", line)
            if match:
                results["skipped"].append(match.group(1))
        elif " ERROR" in line:
            match = re.search(r"(test_\S+)", line)
            if match:
                results["errors"].append(match.group(1))

    # Parse summary line
    summary_match = re.search(
        r"=+ (.+) in [\d.]+s =+", content
    )
    if summary_match:
        results["summary_line"] = summary_match.group(1)

    return results


def collect_screenshots(screenshots_dir: str) -> list:
    """Collect screenshot files with their content."""
    screenshots = []
    dir_path = Path(screenshots_dir)

    if not dir_path.exists():
        return screenshots

    for f in sorted(dir_path.glob("*.txt")):
        screenshots.append({
            "name": f.stem,
            "content": f.read_text(encoding="utf-8")[:500],
        })

    return screenshots


def generate_markdown_report():
    """Generate the markdown report."""
    reports_dir = Path(__file__).parent / "reports"
    log_path = reports_dir / "test_output.log"
    screenshots_dir = reports_dir / "screenshots"

    results = parse_test_output(str(log_path))
    screenshots = collect_screenshots(str(screenshots_dir))

    total = len(results["passed"]) + len(results["failed"]) + len(results["skipped"])
    pass_rate = (
        f"{len(results['passed']) / total * 100:.1f}%" if total > 0 else "N/A"
    )

    report = f"""# Superagent-Base E2E Test Report

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Environment**: localhost:8888 (backend) + localhost:8000 (LLM)
**Model**: Qwen3-Coder-Next-4bit

---

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | {total} |
| Passed | {len(results['passed'])} |
| Failed | {len(results['failed'])} |
| Skipped | {len(results['skipped'])} |
| Pass Rate | {pass_rate} |

"""

    if results.get("summary_line"):
        report += f"**pytest summary**: {results['summary_line']}\n\n"

    # Test categories
    report += "---\n\n## Test Results by Category\n\n"

    categories = {
        "Health Check": "test_01",
        "Basic Agent": "test_02",
        "Workflow Agent": "test_03",
        "Multi-Agent": "test_04",
        "Management": "test_05",
        "Interrupt/Resume": "test_06",
    }

    for cat_name, prefix in categories.items():
        cat_passed = [t for t in results["passed"] if prefix in t]
        cat_failed = [t for t in results["failed"] if prefix in t]
        cat_skipped = [t for t in results["skipped"] if prefix in t]

        if cat_passed or cat_failed or cat_skipped:
            status = "PASS" if not cat_failed else "FAIL"
            emoji = "+" if not cat_failed else "-"
            report += f"### {cat_name} [{status}]\n\n"

            for t in cat_passed:
                report += f"- [x] {t}\n"
            for t in cat_failed:
                report += f"- [ ] {t} **FAILED**\n"
            for t in cat_skipped:
                report += f"- [ ] {t} _(skipped)_\n"
            report += "\n"

    # Screenshots / Evidence
    if screenshots:
        report += "---\n\n## Test Evidence (Screenshots)\n\n"
        for ss in screenshots[:20]:  # Limit to 20
            report += f"### {ss['name']}\n\n```\n{ss['content']}\n```\n\n"

    # Failed test details
    if results["failed"]:
        report += "---\n\n## Failed Tests\n\n"
        report += "See `reports/report.html` for full stack traces.\n\n"
        for t in results["failed"]:
            report += f"- `{t}`\n"

    report += "\n---\n\n*Report generated by `generate_report.py`*\n"

    # Write report
    output_path = reports_dir / "report.md"
    output_path.write_text(report, encoding="utf-8")
    print(f"Markdown report: {output_path}")


if __name__ == "__main__":
    generate_markdown_report()
