/*
 * Copyright 2025 superagent-ai Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package graphs

// This file shows how to drop in an Eino Dev–generated graph.
//
// Workflow:
//  1. Open VS Code with the "Eino Dev" extension connected to :52538.
//  2. Design your graph visually in the IDE.
//  3. Click "Export Go Code" — it produces a Build* function.
//  4. Paste (or save) the generated file here in pkg/graphs/.
//  5. Add an init() block that calls graphs.Register (see below).
//  6. Restart the server: `make dev-server`  (~3 seconds with go run).
//  7. Create or update a YAML agent that references the graph name.
//
// The YAML hot-reload (fsnotify) picks up YAML changes instantly.
// Go graph code requires a restart — which is fast in dev mode.
//
// ─────────────────────────────────────────────────────────────────────────────
// EXAMPLE — paste your Eino Dev output and add the init block:
// ─────────────────────────────────────────────────────────────────────────────
//
//	import (
//	    "context"
//	    "github.com/cloudwego/eino/compose"
//	    "github.com/cloudwego/eino/schema"
//	    "github.com/cloudwego/eino-ext/components/model/openai"
//	)
//
//	// ── generated by Eino Dev ──────────────────────────────────────────────
//	func BuildHelloWorldGraph(ctx context.Context) (*compose.Graph[[]*schema.Message, *schema.Message], error) {
//	    model, _ := openai.NewChatModel(ctx, &openai.ChatModelConfig{...})
//	    g := compose.NewGraph[[]*schema.Message, *schema.Message]()
//	    _ = g.AddChatModelNode("llm", model)
//	    _ = g.AddEdge(compose.START, "llm")
//	    _ = g.AddEdge("llm", compose.END)
//	    return g, nil
//	}
//	// ── end generated code ─────────────────────────────────────────────────
//
//	// Register wires the graph into the superagent runtime.
//	// The name here must match spec.graph in the agent YAML.
//	func init() {
//	    Register("hello-world", CompileGraph(BuildHelloWorldGraph))
//	}
//
// ─────────────────────────────────────────────────────────────────────────────
// YAML (configs/agents/hello-world.yaml):
// ─────────────────────────────────────────────────────────────────────────────
//
//	apiVersion: superagent/v1
//	kind: Agent
//	metadata:
//	  name: hello-world
//	spec:
//	  type: eino_graph
//	  graph: hello-world          # must match the name passed to Register()
//	  system_prompt: "You are a helpful assistant."
