{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superagent.fullname" . }}-secret
  labels:
    {{- include "superagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  MODEL_API_KEY_0: {{ .Values.model.apiKey | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
{{- end }}
